import { test, expect } from "@playwright/test";

/**
 * Manual override (dispatch board → Edit crew) and locking a visit
 * (visits calendar). Both depend on at least one real visit existing for
 * today — generated by `02-generation.spec.ts`, or already present from a real
 * import. Neither manufactures its own visit: a scheduling override only
 * means something against a visit the scheduler (or a manager) actually
 * placed, so this spec adapts to what is really there rather than assuming a
 * fixture that may not exist on every environment.
 */

test("dispatch board: overrides a crew with a reason, and shows every ineligibility reason if the pick fails eligibility", async ({
  page,
}) => {
  await page.goto("/dispatch-board");
  await expect(page.getByRole("heading", { name: "Dispatch Board" })).toBeVisible();

  const editCrewButton = page.getByRole("button", { name: "Edit crew" }).first();
  if ((await editCrewButton.count()) === 0) {
    test.skip(true, "No scheduled visit for today in this environment — nothing to override.");
  }
  await editCrewButton.click();

  await expect(page.getByText(/^Edit crew — /)).toBeVisible();
  await page.getByRole("button", { name: "Add crew member" }).click();
  await page.getByLabel("Employee").click();
  await page.getByRole("option").first().click();

  await page.getByLabel("Reason for this change").fill("E2E: verifying the manual override path");

  const saveButton = page.getByRole("button", { name: "Save assignment" });
  // Ineligible-crew rejection is a real, tested outcome, not a failure of
  // this spec — a hard rule (branch match, PMS supervisor coverage, etc.)
  // is exactly what must never be quietly bypassed.
  const isBlocked = await saveButton.isDisabled();
  if (isBlocked) {
    await expect(page.getByText(/eligible|branch|PMS|inactive|stationed/i).first()).toBeVisible();
    return;
  }

  await saveButton.click();
  await expect(page.getByText(/Assignment saved\.|assignment/i).first()).toBeVisible({ timeout: 10_000 });
});

test("visit calendar: locks and releases a visit", async ({ page }) => {
  await page.goto("/visits");
  await expect(page.getByRole("heading", { name: "Visit Calendar" })).toBeVisible();

  const visitButton = page.locator('button[aria-label*=" at "][aria-label*=" on "]').first();
  if ((await visitButton.count()) === 0) {
    test.skip(true, "No visit on the current month's calendar in this environment.");
  }
  await visitButton.click();

  const lockButton = page.getByRole("button", { name: /Lock this visit|Release this visit/ });
  await expect(lockButton).toBeVisible();
  const wasLocked = (await lockButton.textContent())?.includes("Release") ?? false;

  await lockButton.click();
  await expect(
    page.getByRole("button", { name: wasLocked ? "Lock this visit" : "Release this visit" })
  ).toBeVisible({ timeout: 10_000 });

  // Leave the visit as it was found — this spec observes state, it doesn't
  // decide for the manager whether a real visit should end up locked.
  await page
    .getByRole("button", { name: wasLocked ? "Lock this visit" : "Release this visit" })
    .click();
  await expect(
    page.getByRole("button", { name: wasLocked ? "Release this visit" : "Lock this visit" })
  ).toBeVisible({ timeout: 10_000 });
});
