import { CONFLICT_CODES, ConflictCode } from './conflict-codes';

/** Manager-facing categories used by the Unassigned queue filter. */
export const CONFLICT_GROUPS = [
  'MISSING_PMS',
  'INSUFFICIENT_CREW',
  'MISSING_SKILL',
  'NO_AUTHORIZED_DRIVER',
  'UNAVAILABLE_VEHICLE',
  'BRANCH_RESTRICTION',
  'PERMANENT_STAFF_RESTRICTION',
  'SERVICE_WINDOW_CONFLICT',
  'EMPLOYEE_OVERLAP',
  'VEHICLE_OVERLAP',
  'CREW_CANNOT_TRAVEL',
  'OTHER',
] as const;

export type ConflictGroup = (typeof CONFLICT_GROUPS)[number];

export const CONFLICT_GROUP_CODES: Record<ConflictGroup, readonly ConflictCode[]> = {
  MISSING_PMS: ['NO_PMS_SUPERVISOR_AVAILABLE', 'BRANCH_HAS_NO_PMS_SUPERVISOR'],
  INSUFFICIENT_CREW: ['CREW_TOO_SMALL'],
  MISSING_SKILL: ['SKILL_NOT_HELD'],
  NO_AUTHORIZED_DRIVER: ['NO_AUTHORIZED_DRIVER'],
  UNAVAILABLE_VEHICLE: ['VEHICLE_INACTIVE', 'VEHICLE_CAPACITY_EXCEEDED', 'TOO_MANY_VEHICLES'],
  BRANCH_RESTRICTION: ['BRANCH_MISMATCH', 'VEHICLE_BRANCH_MISMATCH'],
  PERMANENT_STAFF_RESTRICTION: ['EMPLOYEE_PERMANENTLY_STATIONED'],
  SERVICE_WINDOW_CONFLICT: ['OUTSIDE_SERVICE_HOURS', 'WINDOW_TOO_SHORT'],
  EMPLOYEE_OVERLAP: ['EMPLOYEE_DOUBLE_BOOKED', 'DUPLICATE_CREW_MEMBER'],
  VEHICLE_OVERLAP: ['VEHICLE_DOUBLE_BOOKED'],
  CREW_CANNOT_TRAVEL: ['CREW_CANNOT_TRAVEL'],
  OTHER: ['EMPLOYEE_INACTIVE', 'EMPLOYEE_UNAVAILABLE', 'VISIT_NOT_SCHEDULABLE', 'ASSIGNMENT_LOCKED', 'NO_FEASIBLE_CREW'],
};

const GROUPED_CODES = new Set(Object.values(CONFLICT_GROUP_CODES).flat());
const UNGROUPED_CODES = CONFLICT_CODES.filter((code) => !GROUPED_CODES.has(code));
if (UNGROUPED_CODES.length > 0) {
  throw new Error(`Conflict group catalogue is missing: ${UNGROUPED_CODES.join(', ')}`);
}

export const UNASSIGNED_OPERATION_STATES = ['UNASSIGNED', 'EXCEPTION'] as const;
export type UnassignedOperationState = (typeof UNASSIGNED_OPERATION_STATES)[number];
