/**
 * Stable, machine-readable error codes.
 *
 * These are part of the API contract: the manager portal branches on `code`,
 * never on the human-readable `message`. Once a code ships it must not change
 * meaning — add a new code instead.
 *
 * Naming: <DOMAIN>_<CONDITION>.
 */
export const ErrorCode = {
  // --- Generic ---------------------------------------------------------------
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // --- Infrastructure --------------------------------------------------------
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  QUEUE_UNAVAILABLE: 'QUEUE_UNAVAILABLE',
  SCHEDULER_UNAVAILABLE: 'SCHEDULER_UNAVAILABLE',

  // --- Workforce import ------------------------------------------------------
  MATRIX_FILE_NOT_FOUND: 'MATRIX_FILE_NOT_FOUND',
  MATRIX_SHEET_NOT_FOUND: 'MATRIX_SHEET_NOT_FOUND',
  MATRIX_COLUMN_MISSING: 'MATRIX_COLUMN_MISSING',
  MATRIX_ROW_INVALID: 'MATRIX_ROW_INVALID',

  // --- Authentication and authorization --------------------------------------
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',

  // --- Workforce records -----------------------------------------------------
  EMPLOYEE_CODE_TAKEN: 'EMPLOYEE_CODE_TAKEN',
  VEHICLE_CODE_TAKEN: 'VEHICLE_CODE_TAKEN',
  EMPLOYEE_INACTIVE: 'EMPLOYEE_INACTIVE',
  VEHICLE_INACTIVE: 'VEHICLE_INACTIVE',
  PERMANENT_SITE_REQUIRED: 'PERMANENT_SITE_REQUIRED',
  PERMANENT_EMPLOYEE_CANNOT_CHANGE_BRANCH:
    'PERMANENT_EMPLOYEE_CANNOT_CHANGE_BRANCH',
  AUTHORIZATION_ALREADY_EXISTS: 'AUTHORIZATION_ALREADY_EXISTS',
  AUTHORIZATION_NOT_FOUND: 'AUTHORIZATION_NOT_FOUND',
  AVAILABILITY_RANGE_INVALID: 'AVAILABILITY_RANGE_INVALID',
  AVAILABILITY_OVERLAPS: 'AVAILABILITY_OVERLAPS',

  // --- Customers, sites and service agreements -------------------------------
  CUSTOMER_CODE_TAKEN: 'CUSTOMER_CODE_TAKEN',
  JOB_TYPE_CODE_TAKEN: 'JOB_TYPE_CODE_TAKEN',
  SITE_BRANCH_MISMATCH: 'SITE_BRANCH_MISMATCH',
  OPERATING_HOURS_INVALID: 'OPERATING_HOURS_INVALID',
  OPERATING_HOURS_OVERLAP: 'OPERATING_HOURS_OVERLAP',
  SERVICE_WINDOW_INVALID: 'SERVICE_WINDOW_INVALID',
  PREFERRED_DAYS_NOT_ALLOWED: 'PREFERRED_DAYS_NOT_ALLOWED',
  ALLOWED_DAYS_REQUIRED: 'ALLOWED_DAYS_REQUIRED',
  AGREEMENT_DATES_INVALID: 'AGREEMENT_DATES_INVALID',
  AGREEMENT_ARCHIVED: 'AGREEMENT_ARCHIVED',
  AGREEMENT_UNSATISFIABLE: 'AGREEMENT_UNSATISFIABLE',
  SITE_INACTIVE: 'SITE_INACTIVE',
  JOB_TYPE_INACTIVE: 'JOB_TYPE_INACTIVE',
  CUSTOMER_INACTIVE: 'CUSTOMER_INACTIVE',

  // --- Scheduling hard rules (ULK-C05) ---------------------------------------
  //
  // These are the eligibility engine's conflict codes as well as error codes:
  // `scheduling/eligibility/conflict-codes.ts` derives its catalogue from this
  // list rather than keeping a second one. Two vocabularies for the same rule
  // is how a dispatch board ends up filtering on a code the API stopped using.
  ASSIGNMENT_NOT_ELIGIBLE: 'ASSIGNMENT_NOT_ELIGIBLE',
  BRANCH_MISMATCH: 'BRANCH_MISMATCH',
  EMPLOYEE_PERMANENTLY_STATIONED: 'EMPLOYEE_PERMANENTLY_STATIONED',
  NO_PMS_SUPERVISOR_AVAILABLE: 'NO_PMS_SUPERVISOR_AVAILABLE',
  NO_AUTHORIZED_DRIVER: 'NO_AUTHORIZED_DRIVER',
  VEHICLE_CAPACITY_EXCEEDED: 'VEHICLE_CAPACITY_EXCEEDED',
  EMPLOYEE_DOUBLE_BOOKED: 'EMPLOYEE_DOUBLE_BOOKED',
  VEHICLE_DOUBLE_BOOKED: 'VEHICLE_DOUBLE_BOOKED',
  OUTSIDE_SERVICE_HOURS: 'OUTSIDE_SERVICE_HOURS',
  DAY_NOT_ALLOWED: 'DAY_NOT_ALLOWED',
  SKILL_NOT_HELD: 'SKILL_NOT_HELD',
  ASSIGNMENT_LOCKED: 'ASSIGNMENT_LOCKED',
  // EMPLOYEE_INACTIVE and VEHICLE_INACTIVE are already declared above, under
  // the workforce codes, and mean the same thing here.
  EMPLOYEE_UNAVAILABLE: 'EMPLOYEE_UNAVAILABLE',
  /// Distinct from NO_PMS_SUPERVISOR_AVAILABLE: the branch employs none at all,
  /// so "add a supervisor" is not advice anyone can act on. Kandy, today.
  BRANCH_HAS_NO_PMS_SUPERVISOR: 'BRANCH_HAS_NO_PMS_SUPERVISOR',
  CREW_TOO_SMALL: 'CREW_TOO_SMALL',
  DUPLICATE_CREW_MEMBER: 'DUPLICATE_CREW_MEMBER',
  VEHICLE_BRANCH_MISMATCH: 'VEHICLE_BRANCH_MISMATCH',
  WINDOW_TOO_SHORT: 'WINDOW_TOO_SHORT',
  VISIT_NOT_SCHEDULABLE: 'VISIT_NOT_SCHEDULABLE',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
