import type { ServiceAgreementDayRule, ServiceSite, Weekday } from "@/lib/mock-data/types";

/**
 * A client-side estimate only — it exists so a manager can sanity-check an
 * agreement before saving, not to decide the real schedule. The actual
 * schedule (crew, vehicle, published dates) is generated by the scheduling
 * service (ULK-C06+), which also owns every hard rule. This preview never
 * assigns a crew or vehicle and is never treated as authoritative.
 */
export interface SchedulePreviewInput {
  frequencyCount: number;
  frequencyUnit: "WEEK" | "MONTH";
  dayRules: ServiceAgreementDayRule[];
  startDate: string;
  endDate: string | null;
  site: ServiceSite;
  serviceWindowStartMinute: number | null;
  serviceWindowEndMinute: number | null;
  horizonWeeks?: number;
}

export interface SchedulePreviewVisit {
  date: string;
  weekday: Weekday;
  windowStartMinute: number;
  windowEndMinute: number;
  isPreferredDay: boolean;
}

export class SchedulePreviewError extends Error {}

const WEEKDAY_FROM_JS_DAY: Weekday[] = [
  "SUNDAY",
  "MONDAY",
  "TUESDAY",
  "WEDNESDAY",
  "THURSDAY",
  "FRIDAY",
  "SATURDAY",
];

function toDateOnly(value: Date): string {
  return value.toISOString().slice(0, 10);
}

/** ISO week number relative to the horizon start, used to group "N per week". */
function periodKey(date: Date, start: Date, unit: "WEEK" | "MONTH"): number {
  if (unit === "MONTH") return date.getUTCFullYear() * 12 + date.getUTCMonth();
  const days = Math.floor((date.getTime() - start.getTime()) / (24 * 60 * 60 * 1000));
  return Math.floor(days / 7);
}

/**
 * Estimates the next few visit dates for an agreement, given its allowed
 * days, frequency, and the site's per-weekday opening hours. Simulated as
 * async (with a small delay and a rejection path) so the UI exercises the
 * same loading/error states it will need once this becomes a real endpoint
 * call — swapping to `fetch` later should not change the component code.
 */
export async function computeSchedulePreview(
  input: SchedulePreviewInput
): Promise<SchedulePreviewVisit[]> {
  await new Promise((resolve) => setTimeout(resolve, 150));

  const allowedDays = new Set(
    input.dayRules.filter((rule) => rule.kind === "ALLOWED").map((rule) => rule.weekday)
  );
  const preferredDays = new Set(
    input.dayRules.filter((rule) => rule.kind === "PREFERRED").map((rule) => rule.weekday)
  );

  if (allowedDays.size === 0) {
    throw new SchedulePreviewError("Select at least one allowed day to preview the schedule.");
  }
  if (!input.startDate) {
    throw new SchedulePreviewError("Set a start date to preview the schedule.");
  }
  if (input.frequencyCount < 1) {
    throw new SchedulePreviewError("Visits per period must be at least 1.");
  }

  const start = new Date(`${input.startDate}T00:00:00Z`);
  const cap = input.endDate ? new Date(`${input.endDate}T00:00:00Z`) : null;
  const horizonWeeks = input.horizonWeeks ?? 4;
  const horizonEnd = new Date(start);
  horizonEnd.setUTCDate(horizonEnd.getUTCDate() + horizonWeeks * 7);

  const candidates: SchedulePreviewVisit[] = [];
  const cursor = new Date(start);
  while (cursor <= horizonEnd && (!cap || cursor <= cap)) {
    const weekday = WEEKDAY_FROM_JS_DAY[cursor.getUTCDay()];
    if (allowedDays.has(weekday)) {
      const siteHours = input.site.operatingHours.find((entry) => entry.weekday === weekday);
      const windowStart = input.serviceWindowStartMinute ?? siteHours?.opensAtMinute ?? null;
      const windowEnd = input.serviceWindowEndMinute ?? siteHours?.closesAtMinute ?? null;
      if (windowStart !== null && windowEnd !== null) {
        candidates.push({
          date: toDateOnly(cursor),
          weekday,
          windowStartMinute: windowStart,
          windowEndMinute: windowEnd,
          isPreferredDay: preferredDays.has(weekday),
        });
      }
    }
    cursor.setUTCDate(cursor.getUTCDate() + 1);
  }

  // Within each week/month, preferred days rank ahead of merely-allowed ones —
  // the same "preferred is a soft ranking preference" rule the API will apply
  // for real, just illustrated here for the preview.
  const byPeriod = new Map<number, SchedulePreviewVisit[]>();
  for (const visit of candidates) {
    const key = periodKey(new Date(`${visit.date}T00:00:00Z`), start, input.frequencyUnit);
    const bucket = byPeriod.get(key) ?? [];
    bucket.push(visit);
    byPeriod.set(key, bucket);
  }

  const selected: SchedulePreviewVisit[] = [];
  for (const bucket of byPeriod.values()) {
    bucket.sort((a, b) => {
      if (a.isPreferredDay !== b.isPreferredDay) return a.isPreferredDay ? -1 : 1;
      return a.date.localeCompare(b.date);
    });
    selected.push(...bucket.slice(0, input.frequencyCount));
  }

  return selected.sort((a, b) => a.date.localeCompare(b.date));
}
