import type {
  Customer,
  JobType,
  ServiceAgreement,
  Employee,
  Vehicle,
  DispatchVisit,
  UnassignedVisit,
} from "./types";

export const mockJobTypes: JobType[] = [
  {
    id: "job-1",
    code: "TERMITE_CONTROL",
    name: "Termite control",
    defaultDurationMinutes: 90,
    defaultCrewSize: 2,
    requiresPmsSupervisor: true,
    requiredSkillCode: "TERMITE",
    isActive: true,
  },
  {
    id: "job-2",
    code: "GENERAL_PEST",
    name: "General pest control",
    defaultDurationMinutes: 60,
    defaultCrewSize: 1,
    requiresPmsSupervisor: true,
    requiredSkillCode: "GENERAL_PEST",
    isActive: true,
  },
  {
    id: "job-3",
    code: "FUMIGATION",
    name: "Fumigation",
    defaultDurationMinutes: 120,
    defaultCrewSize: 3,
    requiresPmsSupervisor: true,
    requiredSkillCode: "FUMIGATION",
    isActive: true,
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "cust-1",
    name: "Cinnamon Grand Colombo",
    customerCode: "C-001",
    branchCode: "COLOMBO",
    contactName: "R. Gunawardena",
    contactPhone: "011 123 4567",
    contactEmail: "facilities@cinnamongrand.example",
    isActive: true,
    sites: [
      {
        id: "site-1",
        customerId: "cust-1",
        name: "Main Kitchen",
        addressLine: "77 Galle Road",
        city: "Colombo 03",
        branchCode: "COLOMBO",
        isActive: true,
        operatingHours: [
          { weekday: "MONDAY", opensAtMinute: 6 * 60, closesAtMinute: 22 * 60 },
          { weekday: "TUESDAY", opensAtMinute: 6 * 60, closesAtMinute: 22 * 60 },
          { weekday: "WEDNESDAY", opensAtMinute: 6 * 60, closesAtMinute: 22 * 60 },
          { weekday: "THURSDAY", opensAtMinute: 6 * 60, closesAtMinute: 22 * 60 },
          { weekday: "FRIDAY", opensAtMinute: 6 * 60, closesAtMinute: 23 * 60 },
        ],
      },
      {
        id: "site-2",
        customerId: "cust-1",
        name: "Banquet Hall",
        addressLine: "77 Galle Road",
        city: "Colombo 03",
        branchCode: "COLOMBO",
        isActive: true,
        operatingHours: [
          { weekday: "SATURDAY", opensAtMinute: 8 * 60, closesAtMinute: 20 * 60 },
          { weekday: "SUNDAY", opensAtMinute: 8 * 60, closesAtMinute: 20 * 60 },
        ],
      },
    ],
  },
  {
    id: "cust-2",
    name: "Kandy City Centre",
    customerCode: "C-002",
    branchCode: "KANDY",
    contactName: null,
    contactPhone: null,
    contactEmail: null,
    isActive: true,
    sites: [
      {
        id: "site-3",
        customerId: "cust-2",
        name: "Food Court",
        addressLine: "5 Dalada Veediya",
        city: "Kandy",
        branchCode: "KANDY",
        isActive: true,
        operatingHours: [
          { weekday: "MONDAY", opensAtMinute: 9 * 60, closesAtMinute: 21 * 60 },
          { weekday: "WEDNESDAY", opensAtMinute: 9 * 60, closesAtMinute: 21 * 60 },
          { weekday: "FRIDAY", opensAtMinute: 9 * 60, closesAtMinute: 21 * 60 },
        ],
      },
    ],
  },
];

export const mockServiceAgreements: ServiceAgreement[] = [
  {
    id: "sa-1",
    customerId: "cust-1",
    customerName: "Cinnamon Grand Colombo",
    serviceSiteId: "site-1",
    siteName: "Main Kitchen",
    jobTypeId: "job-1",
    jobTypeName: "Termite control",
    branchCode: "COLOMBO",
    frequencyCount: 2,
    frequencyUnit: "WEEK",
    crewSize: 2,
    durationMinutes: 90,
    serviceWindowStartMinute: null,
    serviceWindowEndMinute: null,
    startDate: "2026-01-06",
    endDate: null,
    isActive: true,
    notes: null,
    dayRules: [
      { weekday: "MONDAY", kind: "ALLOWED" },
      { weekday: "TUESDAY", kind: "ALLOWED" },
      { weekday: "THURSDAY", kind: "ALLOWED" },
      { weekday: "MONDAY", kind: "PREFERRED" },
    ],
  },
];

export const mockVehicles: Vehicle[] = [
  { id: "veh-1", code: "COL-4521", label: "Van — COL-4521", branchCode: "COLOMBO", seatCapacity: 6, isActive: true },
  { id: "veh-2", code: "COL-7788", label: "Pickup — COL-7788", branchCode: "COLOMBO", seatCapacity: 3, isActive: true },
  { id: "veh-3", code: "KAN-1190", label: "Van — KAN-1190", branchCode: "KANDY", seatCapacity: 6, isActive: true },
  { id: "veh-4", code: "KAN-2004", label: "Pickup — KAN-2004", branchCode: "KANDY", seatCapacity: 3, isActive: true },
];

export const mockEmployees: Employee[] = [
  {
    id: "emp-1",
    employeeCode: "E-101",
    fullName: "S. Perera",
    gradeLabel: "PMS",
    isPmsGrade: true,
    branchCode: "COLOMBO",
    deploymentType: "MOBILE",
    permanentSiteLabel: null,
    isActive: true,
    skills: [
      { skillCode: "FUMIGATION", skillLabel: "Fumigation" },
      { skillCode: "TERMITE", skillLabel: "Termite Control" },
    ],
    authorizedVehicleIds: ["veh-1", "veh-2"],
  },
  {
    id: "emp-2",
    employeeCode: "E-102",
    fullName: "N. Fernando",
    gradeLabel: "Junior PMT",
    isPmsGrade: false,
    branchCode: "KANDY",
    deploymentType: "MOBILE",
    permanentSiteLabel: null,
    isActive: true,
    skills: [{ skillCode: "GENERAL_PEST", skillLabel: "General Pest Control" }],
    authorizedVehicleIds: ["veh-3"],
  },
  {
    id: "emp-3",
    employeeCode: "E-103",
    fullName: "A. Silva",
    gradeLabel: "Senior PMS",
    isPmsGrade: true,
    branchCode: "COLOMBO",
    deploymentType: "PERMANENTLY_STATIONED",
    permanentSiteLabel: "Grandview Hotel",
    isActive: true,
    skills: [{ skillCode: "FUMIGATION", skillLabel: "Fumigation" }],
    authorizedVehicleIds: [],
  },
  {
    id: "emp-4",
    employeeCode: "E-104",
    fullName: "R. Bandara",
    gradeLabel: "Assistant PMS",
    isPmsGrade: true,
    branchCode: "COLOMBO",
    deploymentType: "MOBILE",
    permanentSiteLabel: null,
    isActive: true,
    skills: [
      { skillCode: "TERMITE", skillLabel: "Termite Control" },
      { skillCode: "RODENT", skillLabel: "Rodent Control" },
    ],
    authorizedVehicleIds: ["veh-1"],
  },
  {
    id: "emp-5",
    employeeCode: "E-105",
    fullName: "K. Jayasuriya",
    gradeLabel: "PMS",
    isPmsGrade: true,
    branchCode: "KANDY",
    deploymentType: "MOBILE",
    permanentSiteLabel: null,
    isActive: true,
    skills: [{ skillCode: "FUMIGATION", skillLabel: "Fumigation" }],
    authorizedVehicleIds: ["veh-3"],
  },
  {
    id: "emp-6",
    employeeCode: "E-106",
    fullName: "T. Wickrama",
    gradeLabel: "Junior PMT",
    isPmsGrade: false,
    branchCode: "COLOMBO",
    deploymentType: "PERMANENTLY_STATIONED",
    permanentSiteLabel: "Seaside Resort",
    isActive: false,
    skills: [{ skillCode: "GENERAL_PEST", skillLabel: "General Pest Control" }],
    authorizedVehicleIds: [],
  },
];

export const mockDispatchVisits: DispatchVisit[] = [
  {
    id: "visit-1",
    customerName: "Cinnamon Grand Colombo",
    branchCode: "COLOMBO",
    scheduledDate: "2026-08-24",
    crewEmployeeNames: ["S. Perera"],
    hasPmsSupervisor: true,
  },
];

export const mockUnassignedVisits: UnassignedVisit[] = [
  {
    id: "unassigned-1",
    customerName: "Kandy City Centre",
    branchCode: "KANDY",
    reason: "No PMS-grade supervisor available in Kandy for the preferred day.",
  },
];
